graph LR;
navigation["navigation<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation.PNG' width='100'/>"]:::transparentNode
admin_PNG_Zone["admin.PNG:Zone"]:::transparentNode
navigation --> admin_PNG_Zone
website_PNG_Zone["website.PNG:Zone"]:::transparentNode
navigation --> website_PNG_Zone
website["website<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/./02 - website.PNG' width='100'/>"]:::transparentNode
click website "https://storage.googleapis.com/pruebasautomatizadas-ghost/./02 - website.PNG"
navigation --> website
admin["admin<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01 - admin.PNG' width='100'/>"]:::transparentNode
click admin "https://storage.googleapis.com/pruebasautomatizadas-ghost/./01 - admin.PNG"
navigation --> admin
click admin "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01 - admin.PNG"
admin --> admin
posts_PNG_Zone["posts.PNG:Zone"]:::transparentNode
admin --> posts_PNG_Zone
view_site["view_site<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/02 - view_site.PNG' width='100'/>"]:::transparentNode
click view_site "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/02 - view_site.PNG"
admin --> view_site
members["members<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members.PNG' width='100'/>"]:::transparentNode
click members "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members.PNG"
admin --> members
view_site_PNG_Zone["view_site.PNG:Zone"]:::transparentNode
admin --> view_site_PNG_Zone
tags["tags<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags.PNG' width='100'/>"]:::transparentNode
click tags "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags.PNG"
admin --> tags
explore["explore<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/03 - explore.PNG' width='100'/>"]:::transparentNode
click explore "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/03 - explore.PNG"
admin --> explore
dashboard["dashboard<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/01 - dashboard.PNG' width='100'/>"]:::transparentNode
click dashboard "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/01 - dashboard.PNG"
admin --> dashboard
profile["profile<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile.PNG' width='100'/>"]:::transparentNode
click profile "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile.PNG"
admin --> profile
tags_PNG_Zone["tags.PNG:Zone"]:::transparentNode
admin --> tags_PNG_Zone
pages_PNG_Zone["pages.PNG:Zone"]:::transparentNode
admin --> pages_PNG_Zone
settings_PNG_Zone["settings.PNG:Zone"]:::transparentNode
admin --> settings_PNG_Zone
pages["pages<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages.PNG' width='100'/>"]:::transparentNode
click pages "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages.PNG"
admin --> pages
posts["posts<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts.PNG' width='100'/>"]:::transparentNode
click posts "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts.PNG"
admin --> posts
settings["settings<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings.PNG' width='100'/>"]:::transparentNode
click settings "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings.PNG"
admin --> settings
members_PNG_Zone["members.PNG:Zone"]:::transparentNode
admin --> members_PNG_Zone
explore_PNG_Zone["explore.PNG:Zone"]:::transparentNode
admin --> explore_PNG_Zone
dashboard_PNG_Zone["dashboard.PNG:Zone"]:::transparentNode
admin --> dashboard_PNG_Zone
profile_PNG_Zone["profile.PNG:Zone"]:::transparentNode
admin --> profile_PNG_Zone
help_center_png_Zone["help_center.png:Zone"]:::transparentNode
profile --> help_center_png_Zone
whats_new["whats_new<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/01 - whats_new.png' width='100'/>"]:::transparentNode
click whats_new "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/01 - whats_new.png"
profile --> whats_new
resources_and_guides_PNG_Zone["resources_and_guides.PNG:Zone"]:::transparentNode
profile --> resources_and_guides_PNG_Zone
whats_new_png_Zone["whats_new.png:Zone"]:::transparentNode
profile --> whats_new_png_Zone
help_center["help_center<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/03 - help_center.png' width='100'/>"]:::transparentNode
click help_center "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/03 - help_center.png"
profile --> help_center
your_profile["your_profile<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/02 - your_profile.PNG' width='100'/>"]:::transparentNode
click your_profile "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/02 - your_profile.PNG"
profile --> your_profile
your_profile_PNG_Zone["your_profile.PNG:Zone"]:::transparentNode
profile --> your_profile_PNG_Zone
resources_and_guides["resources_and_guides<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/04 - resources_and_guides.PNG' width='100'/>"]:::transparentNode
click resources_and_guides "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/04 - resources_and_guides.PNG"
profile --> resources_and_guides
change_password["change_password<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/02 - your_profile/01 - change_password.PNG' width='100'/>"]:::transparentNode
click change_password "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/08 - profile/02 - your_profile/01 - change_password.PNG"
your_profile --> change_password
create_post["create_post<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post.PNG' width='100'/>"]:::transparentNode
click create_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post.PNG"
posts --> create_post
create_post_PNG_Zone["create_post.PNG:Zone"]:::transparentNode
posts --> create_post_PNG_Zone
preview_post_social["preview_post_social<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/04 - preview_post_social.PNG' width='100'/>"]:::transparentNode
click preview_post_social "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/04 - preview_post_social.PNG"
create_post --> preview_post_social
preview_post["preview_post<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/01 - preview_post.PNG' width='100'/>"]:::transparentNode
click preview_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/01 - preview_post.PNG"
create_post --> preview_post
preview_post_mobile["preview_post_mobile<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/02 - preview_post_mobile.PNG' width='100'/>"]:::transparentNode
click preview_post_mobile "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/02 - preview_post_mobile.PNG"
create_post --> preview_post_mobile
preview_post_mobile_PNG_Zone["preview_post_mobile.PNG:Zone"]:::transparentNode
create_post --> preview_post_mobile_PNG_Zone
preview_post_social_PNG_Zone["preview_post_social.PNG:Zone"]:::transparentNode
create_post --> preview_post_social_PNG_Zone
preview_post_mail_PNG_Zone["preview_post_mail.PNG:Zone"]:::transparentNode
create_post --> preview_post_mail_PNG_Zone
share_post["share_post<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/05 - share_post.PNG' width='100'/>"]:::transparentNode
click share_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/05 - share_post.PNG"
create_post --> share_post
share_post_PNG_Zone["share_post.PNG:Zone"]:::transparentNode
create_post --> share_post_PNG_Zone
preview_post_mail["preview_post_mail<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/03 - preview_post_mail.PNG' width='100'/>"]:::transparentNode
click preview_post_mail "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/03 - preview_post_mail.PNG"
create_post --> preview_post_mail
preview_post_PNG_Zone["preview_post.PNG:Zone"]:::transparentNode
create_post --> preview_post_PNG_Zone
finish_post_PNG_Zone["finish_post.PNG:Zone"]:::transparentNode
share_post --> finish_post_PNG_Zone
finish_post["finish_post<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/05 - share_post/01 - finish_post.PNG' width='100'/>"]:::transparentNode
click finish_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/04 - posts/01 - create_post/05 - share_post/01 - finish_post.PNG"
share_post --> finish_post
import_members["import_members<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/02 - import_members.PNG' width='100'/>"]:::transparentNode
click import_members "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/02 - import_members.PNG"
members --> import_members
filters["filters<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/03 - filters.PNG' width='100'/>"]:::transparentNode
click filters "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/03 - filters.PNG"
members --> filters
create_member["create_member<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/01 - create_member.PNG' width='100'/>"]:::transparentNode
click create_member "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/07 - members/01 - create_member.PNG"
members --> create_member
create_member_PNG_Zone["create_member.PNG:Zone"]:::transparentNode
members --> create_member_PNG_Zone
delete["delete<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/07 - delete/01 - delete.PNG' width='100'/>"]:::transparentNode
settings --> delete
click delete "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/07 - delete/01 - delete.PNG"
delete --> delete
confirm_delete["confirm_delete<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/07 - delete/01 - delete/01 - confirm_delete.PNG' width='100'/>"]:::transparentNode
click confirm_delete "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/07 - delete/01 - delete/01 - confirm_delete.PNG"
delete --> confirm_delete
email_newsletter["email_newsletter"]:::transparentNode
settings --> email_newsletter
default_recipients["default_recipients<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/02 - default_recipients.PNG' width='100'/>"]:::transparentNode
click default_recipients "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/02 - default_recipients.PNG"
email_newsletter --> default_recipients
newsletter_sending["newsletter_sending<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/01 - newsletter_sending.PNG' width='100'/>"]:::transparentNode
click newsletter_sending "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/01 - newsletter_sending.PNG"
email_newsletter --> newsletter_sending
mailgun_settings["mailgun_settings<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/04 - mailgun_settings/01 - mailgun_settings.PNG' width='100'/>"]:::transparentNode
email_newsletter --> mailgun_settings
click mailgun_settings "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/04 - mailgun_settings/01 - mailgun_settings.PNG"
mailgun_settings --> mailgun_settings
newsletters["newsletters"]:::transparentNode
email_newsletter --> newsletters
archived_newsletter["archived_newsletter<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/02 - archived_newsletter.PNG' width='100'/>"]:::transparentNode
click archived_newsletter "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/02 - archived_newsletter.PNG"
newsletters --> archived_newsletter
active_newsletter["active_newsletter<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter.PNG' width='100'/>"]:::transparentNode
click active_newsletter "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter.PNG"
newsletters --> active_newsletter
create_newsletter_PNG_Zone["create_newsletter.PNG:Zone"]:::transparentNode
newsletters --> create_newsletter_PNG_Zone
create_newsletter["create_newsletter<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/03 - create_newsletter.PNG' width='100'/>"]:::transparentNode
click create_newsletter "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/03 - create_newsletter.PNG"
newsletters --> create_newsletter
edit_newsletter_general_PNG_Zone["edit_newsletter_general.PNG:Zone"]:::transparentNode
active_newsletter --> edit_newsletter_general_PNG_Zone
edit_newsletter_general["edit_newsletter_general<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general.PNG' width='100'/>"]:::transparentNode
click edit_newsletter_general "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general.PNG"
active_newsletter --> edit_newsletter_general
view_PNG_Zone["view.PNG:Zone"]:::transparentNode
edit_newsletter_general --> view_PNG_Zone
view["view<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/01 - view.PNG' width='100'/>"]:::transparentNode
click view "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/01 - view.PNG"
edit_newsletter_general --> view
design_PNG_Zone["design.PNG:Zone"]:::transparentNode
edit_newsletter_general --> design_PNG_Zone
design["design<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/03 - design.PNG' width='100'/>"]:::transparentNode
click design "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/03 - design.PNG"
edit_newsletter_general --> design
general["general<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/02 - general.PNG' width='100'/>"]:::transparentNode
click general "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/05 - email_newsletter/03 - newsletters/01 - active_newsletter/01 - edit_newsletter_general/02 - general.PNG"
edit_newsletter_general --> general
general_PNG_Zone["general.PNG:Zone"]:::transparentNode
edit_newsletter_general --> general_PNG_Zone
membership["membership"]:::transparentNode
settings --> membership
access["access<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/02 - access.PNG' width='100'/>"]:::transparentNode
click access "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/02 - access.PNG"
membership --> access
portal_settings["portal_settings<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings.PNG' width='100'/>"]:::transparentNode
click portal_settings "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings.PNG"
membership --> portal_settings
access_PNG_Zone["access.PNG:Zone"]:::transparentNode
membership --> access_PNG_Zone
tiers["tiers<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers.PNG' width='100'/>"]:::transparentNode
click tiers "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers.PNG"
membership --> tiers
analytics["analytics<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/04 - analytics/01 - analytics.PNG' width='100'/>"]:::transparentNode
membership --> analytics
click analytics "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/04 - analytics/01 - analytics.PNG"
analytics --> analytics
get_paid["get_paid<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid.PNG' width='100'/>"]:::transparentNode
click get_paid "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid.PNG"
tiers --> get_paid
connect_with_stripe["connect_with_stripe<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid/01 - connect_with_stripe.PNG' width='100'/>"]:::transparentNode
click connect_with_stripe "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid/01 - connect_with_stripe.PNG"
get_paid --> connect_with_stripe
stripe["stripe<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid/01 - connect_with_stripe/stripe.PNG' width='100'/>"]:::transparentNode
click stripe "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/03 - tiers/01 - get_paid/01 - connect_with_stripe/stripe.PNG"
connect_with_stripe --> stripe
look_and_feel_PNG_Zone["look_and_feel.PNG:Zone"]:::transparentNode
portal_settings --> look_and_feel_PNG_Zone
links_PNG_Zone["links.PNG:Zone"]:::transparentNode
portal_settings --> links_PNG_Zone
signup["signup<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/01a - signup.PNG' width='100'/>"]:::transparentNode
click signup "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/01a - signup.PNG"
portal_settings --> signup
links["links<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/03a - links.PNG' width='100'/>"]:::transparentNode
click links "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/03a - links.PNG"
portal_settings --> links
signup_options["signup_options<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/01b - signup_options.PNG' width='100'/>"]:::transparentNode
click signup_options "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/01b - signup_options.PNG"
portal_settings --> signup_options
look_and_feel["look_and_feel<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/02b - look_and_feel.PNG' width='100'/>"]:::transparentNode
click look_and_feel "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/02b - look_and_feel.PNG"
portal_settings --> look_and_feel
account_page["account_page<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/03b - account_page.PNG' width='100'/>"]:::transparentNode
click account_page "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/03 - membership/01 - portal_settings/03b - account_page.PNG"
portal_settings --> account_page
signup_options_PNG_Zone["signup_options.PNG:Zone"]:::transparentNode
portal_settings --> signup_options_PNG_Zone
signup_PNG_Zone["signup.PNG:Zone"]:::transparentNode
portal_settings --> signup_PNG_Zone
account_page_PNG_Zone["account_page.PNG:Zone"]:::transparentNode
portal_settings --> account_page_PNG_Zone
advanced["advanced"]:::transparentNode
settings --> advanced
labs["labs<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/05 - labs.PNG' width='100'/>"]:::transparentNode
click labs "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/05 - labs.PNG"
advanced --> labs
historyx["historyx<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/06 - historyx.PNG' width='100'/>"]:::transparentNode
click historyx "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/06 - historyx.PNG"
advanced --> historyx
spam_filters["spam_filters<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/03 - spam_filters.PNG' width='100'/>"]:::transparentNode
click spam_filters "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/03 - spam_filters.PNG"
advanced --> spam_filters
code_injection["code_injection<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/04 - code_injection.PNG' width='100'/>"]:::transparentNode
click code_injection "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/04 - code_injection.PNG"
advanced --> code_injection
import_export["import_export"]:::transparentNode
advanced --> import_export
migration_tools["migration_tools"]:::transparentNode
import_export --> migration_tools
import_migration_tools["import_migration_tools<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/02 - import_export/01 - migration_tools/01 - import_migration_tools.PNG' width='100'/>"]:::transparentNode
click import_migration_tools "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/02 - import_export/01 - migration_tools/01 - import_migration_tools.PNG"
migration_tools --> import_migration_tools
export_migration_tools["export_migration_tools<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/02 - import_export/01 - migration_tools/02 - export_migration_tools.PNG' width='100'/>"]:::transparentNode
click export_migration_tools "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/02 - import_export/01 - migration_tools/02 - export_migration_tools.PNG"
migration_tools --> export_migration_tools
history["history<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/06 - history/01 - history.PNG' width='100'/>"]:::transparentNode
advanced --> history
click history "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/06 - history/01 - history.PNG"
history --> history
integrations["integrations"]:::transparentNode
advanced --> integrations
custom_integrationsw["custom_integrationsw<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/02 - custom_integrationsw.PNG' width='100'/>"]:::transparentNode
click custom_integrationsw "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/02 - custom_integrationsw.PNG"
integrations --> custom_integrationsw
add_integration["add_integration<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration.PNG' width='100'/>"]:::transparentNode
click add_integration "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration.PNG"
integrations --> add_integration
built_in_integrations["built_in_integrations<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations.PNG' width='100'/>"]:::transparentNode
click built_in_integrations "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations.PNG"
integrations --> built_in_integrations
integration_example["integration_example<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration/01 - integration_example.PNG' width='100'/>"]:::transparentNode
click integration_example "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration/01 - integration_example.PNG"
add_integration --> integration_example
add_web_hook["add_web_hook<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration/01 - integration_example/01 - add_web_hook.PNG' width='100'/>"]:::transparentNode
click add_web_hook "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/03 - add_integration/01 - integration_example/01 - add_web_hook.PNG"
integration_example --> add_web_hook
custom_integrations["custom_integrations"]:::transparentNode
integrations --> custom_integrations
delete_custom_integration["delete_custom_integration<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/02 - custom_integrations/01 - delete_custom_integration.PNG' width='100'/>"]:::transparentNode
click delete_custom_integration "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/02 - custom_integrations/01 - delete_custom_integration.PNG"
custom_integrations --> delete_custom_integration
zapier_PNG_Zone["zapier.PNG:Zone"]:::transparentNode
built_in_integrations --> zapier_PNG_Zone
slack["slack<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/02 - slack.PNG' width='100'/>"]:::transparentNode
click slack "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/02 - slack.PNG"
built_in_integrations --> slack
zapier["zapier<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/01 - zapier.PNG' width='100'/>"]:::transparentNode
click zapier "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/01 - zapier.PNG"
built_in_integrations --> zapier
first_promoter["first_promoter<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/04 - first_promoter.PNG' width='100'/>"]:::transparentNode
click first_promoter "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/04 - first_promoter.PNG"
built_in_integrations --> first_promoter
unsplash["unsplash<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/03 - unsplash.PNG' width='100'/>"]:::transparentNode
click unsplash "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/03 - unsplash.PNG"
built_in_integrations --> unsplash
pintura["pintura<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/05 - pintura.PNG' width='100'/>"]:::transparentNode
click pintura "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/01 - integrations/01 - built_in_integrations/05 - pintura.PNG"
built_in_integrations --> pintura
site_header_PNG_Zone["site_header.PNG:Zone"]:::transparentNode
code_injection --> site_header_PNG_Zone
site_footer["site_footer<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/04 - code_injection/02 - site_footer.PNG' width='100'/>"]:::transparentNode
click site_footer "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/04 - code_injection/02 - site_footer.PNG"
code_injection --> site_footer
site_header["site_header<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/04 - code_injection/01 - site_header.PNG' width='100'/>"]:::transparentNode
click site_header "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/06 - advanced/04 - code_injection/01 - site_header.PNG"
code_injection --> site_header
site_footer_PNG_Zone["site_footer.PNG:Zone"]:::transparentNode
code_injection --> site_footer_PNG_Zone
site["site"]:::transparentNode
settings --> site
theme["theme<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/02 - theme/02 - theme/01 - theme.png' width='100'/>"]:::transparentNode
click theme "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/02 - theme.PNG"
site --> theme
design_and_branding["design_and_branding<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/01 - design_and_branding.PNG' width='100'/>"]:::transparentNode
click design_and_branding "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/01 - design_and_branding.PNG"
site --> design_and_branding
click navigation "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation.PNG"
site --> navigation
announcement_bar["announcement_bar<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/04 - announcement_bar/04 - announcement_bar.PNG' width='100'/>"]:::transparentNode
click announcement_bar "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/04 - announcement_bar.PNG"
site --> announcement_bar
secondary_PNG_Zone["secondary.PNG:Zone"]:::transparentNode
navigation --> secondary_PNG_Zone
primary["primary<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation/01 - primary.PNG' width='100'/>"]:::transparentNode
click primary "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation/01 - primary.PNG"
navigation --> primary
secondary["secondary<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation/02 - secondary.PNG' width='100'/>"]:::transparentNode
click secondary "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/03 - navigation/02 - secondary.PNG"
navigation --> secondary
primary_PNG_Zone["primary.PNG:Zone"]:::transparentNode
navigation --> primary_PNG_Zone
theme_PNG_Zone["theme.PNG:Zone"]:::transparentNode
theme --> theme_PNG_Zone
click theme "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/02 - theme/01 - theme.PNG"
theme --> theme
click theme "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/02 - theme/02 - theme/01 - theme.png"
theme --> theme
theme_png_Zone["theme.png:Zone"]:::transparentNode
theme --> theme_png_Zone
announcement_bar_PNG_Zone["announcement_bar.PNG:Zone"]:::transparentNode
announcement_bar --> announcement_bar_PNG_Zone
click announcement_bar "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/02 - site/04 - announcement_bar/04 - announcement_bar.PNG"
announcement_bar --> announcement_bar
general_settings["general_settings"]:::transparentNode
settings --> general_settings
publication_language["publication_language<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/03 - publication_language.PNG' width='100'/>"]:::transparentNode
click publication_language "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/03 - publication_language.PNG"
general_settings --> publication_language
staff["staff<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff.PNG' width='100'/>"]:::transparentNode
click staff "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff.PNG"
general_settings --> staff
make_site_private["make_site_private<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/08 - make_site_private.PNG' width='100'/>"]:::transparentNode
click make_site_private "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/08 - make_site_private.PNG"
general_settings --> make_site_private
soccial_accounts["soccial_accounts<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/07 - soccial_accounts.PNG' width='100'/>"]:::transparentNode
click soccial_accounts "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/07 - soccial_accounts.PNG"
general_settings --> soccial_accounts
facebook_card["facebook_card<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/06 - facebook_card.PNG' width='100'/>"]:::transparentNode
click facebook_card "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/06 - facebook_card.PNG"
general_settings --> facebook_card
timezone["timezone<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/02 - timezone.PNG' width='100'/>"]:::transparentNode
click timezone "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/02 - timezone.PNG"
general_settings --> timezone
title_and_description["title_and_description<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/01 - title_and_description.PNG' width='100'/>"]:::transparentNode
click title_and_description "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/01 - title_and_description.PNG"
general_settings --> title_and_description
x_card["x_card<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/05 - x_card.PNG' width='100'/>"]:::transparentNode
click x_card "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/05 - x_card.PNG"
general_settings --> x_card
meta_data["meta_data<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/01 - meta_data.PNG' width='100'/>"]:::transparentNode
click meta_data "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/04 - meta_data.PNG"
general_settings --> meta_data
view_profile_PNG_Zone["view_profile.PNG:Zone"]:::transparentNode
staff --> view_profile_PNG_Zone
view_profile["view_profile<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff/02 - view_profile.PNG' width='100'/>"]:::transparentNode
click view_profile "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff/02 - view_profile.PNG"
staff --> view_profile
invite_people["invite_people<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff/01 - invite_people.PNG' width='100'/>"]:::transparentNode
click invite_people "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/01 - general_settings/09 - staff/01 - invite_people.PNG"
staff --> invite_people
growth["growth"]:::transparentNode
settings --> growth
recommendations["recommendations"]:::transparentNode
growth --> recommendations
recommending_you["recommending_you<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/02 - recommending_you.PNG' width='100'/>"]:::transparentNode
click recommending_you "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/02 - recommending_you.PNG"
recommendations --> recommending_you
add_recommendation["add_recommendation<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/03 - add_recommendation.PNG' width='100'/>"]:::transparentNode
click add_recommendation "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/03 - add_recommendation.PNG"
recommendations --> add_recommendation
your_recommendations["your_recommendations<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/01 - your_recommendations.PNG' width='100'/>"]:::transparentNode
click your_recommendations "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/01 - recommendations/01 - your_recommendations.PNG"
recommendations --> your_recommendations
embeddable_signup_form["embeddable_signup_form"]:::transparentNode
growth --> embeddable_signup_form
enbeddable_signup["enbeddable_signup<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/02 - embeddable_signup_form/01 - enbeddable_signup.PNG' width='100'/>"]:::transparentNode
click enbeddable_signup "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/02 - embeddable_signup_form/01 - enbeddable_signup.PNG"
embeddable_signup_form --> enbeddable_signup
embedded_signup_form["embedded_signup_form<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/02 - embeddable_signup_form/01 - enbeddable_signup/01 - embedded_signup_form.png' width='100'/>"]:::transparentNode
click embedded_signup_form "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/09 - settings/04 - growth/02 - embeddable_signup_form/01 - enbeddable_signup/01 - embedded_signup_form.png"
enbeddable_signup --> embedded_signup_form
embedded_signup_form_png_Zone["embedded_signup_form.png:Zone"]:::transparentNode
enbeddable_signup --> embedded_signup_form_png_Zone
create_page_PNG_Zone["create_page.PNG:Zone"]:::transparentNode
pages --> create_page_PNG_Zone
create_page["create_page<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page.PNG' width='100'/>"]:::transparentNode
click create_page "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page.PNG"
pages --> create_page
click preview_post_social "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/04 - preview_post_social.PNG"
create_page --> preview_post_social
click preview_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/01 - preview_post.PNG"
create_page --> preview_post
click preview_post_mobile "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/02 - preview_post_mobile.PNG"
create_page --> preview_post_mobile
create_page --> preview_post_mobile_PNG_Zone
create_page --> preview_post_social_PNG_Zone
create_page --> preview_post_mail_PNG_Zone
click share_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/05 - share_post.PNG"
create_page --> share_post
create_page --> share_post_PNG_Zone
click preview_post_mail "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/03 - preview_post_mail.PNG"
create_page --> preview_post_mail
create_page --> preview_post_PNG_Zone
share_post --> finish_post_PNG_Zone
click finish_post "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/05 - pages/01 - create_page/05 - share_post/01 - finish_post.PNG"
share_post --> finish_post
additional_PNG_Zone["additional.PNG:Zone"]:::transparentNode
tags --> additional_PNG_Zone
additional["additional<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional.PNG' width='100'/>"]:::transparentNode
click additional "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional.PNG"
tags --> additional
create_tag["create_tag<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/01 - create_tag.PNG' width='100'/>"]:::transparentNode
click create_tag "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/01 - create_tag.PNG"
tags --> create_tag
create_tag_PNG_Zone["create_tag.PNG:Zone"]:::transparentNode
tags --> create_tag_PNG_Zone
meta_data_PNG_Zone["meta_data.PNG:Zone"]:::transparentNode
additional --> meta_data_PNG_Zone
x_PNG_Zone["x.PNG:Zone"]:::transparentNode
additional --> x_PNG_Zone
facebook["facebook<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/03 - facebook.PNG' width='100'/>"]:::transparentNode
click facebook "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/03 - facebook.PNG"
additional --> facebook
code_injection_PNG_Zone["code_injection.PNG:Zone"]:::transparentNode
additional --> code_injection_PNG_Zone
click meta_data "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/01 - meta_data.PNG"
additional --> meta_data
facebook_PNG_Zone["facebook.PNG:Zone"]:::transparentNode
additional --> facebook_PNG_Zone
x["x<br/><img src='https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/02 - x.PNG' width='100'/>"]:::transparentNode
click x "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/02 - x.PNG"
additional --> x
click code_injection "https://storage.googleapis.com/pruebasautomatizadas-ghost/01 - admin/01- admin/06 - tags/02 - additional/04 - code_injection.PNG"
additional --> code_injection
classDef transparentNode fill:#2d2d2d,color:white,stroke:#333,stroke-width:2px,rx:10,ry:10;